### ISSUE TITLE
exported module function does not include members

### ISSUE THREAD

**Issue by alexmingoia** [75lb/dmd#7]
```javascript
/**
 * @module myModule
 */

module.exports = function foo () { ... }

exports.bar = function () { ... }
```
```javascript
{
    "params": [],
    "name": "bar",
    "longname": "module:myModule.bar",
    "kind": "function",
    "memberof": "module:myModule",
    "scope": "static",
    "codeName": "exports.bar"
  },
```

exports.bar is missing from the generated docs... but seems to be parsed correctly in the output of jsdoc-parse. I'll investigate further if I have time. Exporting a class doesn't present this problem.

**Comment by 75lb** [comment]
sup alex.. i packaged up a pre-release version for you to play with.. 

install it
`$ npm install -g jsdoc-to-markdown@next`

then try it for yourself, on say asserted: 
`$ jsdoc2md -t lib/readme.hbs lib/asserted.js > README.md`

take a look at the new options:
`$ jsdoc2md --help`

let me know of any flaws etc :)
